<?php

/**
 * @file
 * Post-update functions for the Canvas AI module.
 */

declare(strict_types=1);

use Drupal\canvas\Plugin\Canvas\ComponentSource\BlockComponent;
use Drupal\canvas\Plugin\Canvas\ComponentSource\JsComponent;
use Drupal\canvas\Plugin\Canvas\ComponentSource\SingleDirectoryComponent;
use Drupal\canvas_ai\CanvasAiPageBuilderHelper;
use Drupal\Component\Serialization\Yaml;
use Drupal\Component\Utility\Crypt;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Config\FileStorage;
use Drupal\Core\Config\StorageCacheInterface;
use Drupal\Core\Config\StorageInterface;
use Drupal\Core\Extension\ModuleExtensionList;
use Drupal\Core\Routing\RouteBuilderInterface;

/**
 * Rebuild the router.
 *
 * Clears the route cache as this issue introduces changes to canvas_ai routes.
 *
 * @see https://www.drupal.org/project/canvas/issues/3533079
 */
function canvas_ai_post_update_0001_rebuild_router(): void {
  \Drupal::service(RouteBuilderInterface::class)->rebuild();
}

/**
 * Preserve the existing chat history limit for existing sites.
 */
function canvas_ai_post_update_0002_chat_history_max_messages(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.settings');

  // Existing sites effectively use a limit of 3, so keep that value here to
  // preserve current behavior. New installations get the newer default of
  // 10 from config/install/canvas_ai.settings.yml.
  if (!$config->isNew()) {
    $config->set('chat_history_max_messages', 3)->save(TRUE);
  }
}

/**
 * Reimport orchestrator agent as system prompt has changed.
 *
 * @see https://www.drupal.org/project/canvas/issues/3582390
 */
function canvas_ai_post_update_0003_reimport_orchestrator_agent(): void {
  $module_path = \Drupal::service(ModuleExtensionList::class)->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $data = $source->read('ai_agents.ai_agent.canvas_ai_orchestrator');
  $config = \Drupal::configFactory()->getEditable('ai_agents.ai_agent.canvas_ai_orchestrator');
  if ($data && !$config->isNew()) {
    // Only the system prompt changed. Set just that key so the per-site uuid,
    // _core hash, and any other fields stay intact.
    $config->set('system_prompt', $data['system_prompt'])->save(TRUE);

    $message = 'The Canvas AI orchestrator agent system prompt has been updated. If you had customized it directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}

/**
 * Enable hostname filter bypass for the Canvas Component Agent.
 *
 * Hostname filtering will interfere with the React code generated by
 * canvas_component_agent, so it must be disabled for the agent to work correctly.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3590309
 */
function canvas_ai_post_update_0004_agent_hostname_filter(): void {
  $config = \Drupal::configFactory()
    ->getEditable('ai_agents.ai_agent.canvas_component_agent');
  if (!$config->isNew() && $config->get('hostname_filter_disabled') !== TRUE) {
    $config->set('hostname_filter_disabled', TRUE)->save(TRUE);
  }
}

/**
 * Normalize component description settings for stricter schema validation.
 */
function canvas_ai_post_update_0005_normalize_component_description_settings(): void {
  $config_factory = Drupal::service(ConfigFactoryInterface::class);
  assert($config_factory instanceof ConfigFactoryInterface);
  $config = $config_factory->getEditable('canvas_ai.component_description.settings');

  if ($config->isNew()) {
    // The settings form creates this config on first save. Sites that never
    // saved it have no active config to normalize.
    return;
  }

  $context = $config->get('component_context') ?? [];
  $allowed_sources = [
    SingleDirectoryComponent::SOURCE_PLUGIN_ID,
    JsComponent::SOURCE_PLUGIN_ID,
    BlockComponent::SOURCE_PLUGIN_ID,
  ];
  $migrated = [];

  // Active configuration may predate schema validation or have been imported
  // with invalid values, so normalize only the array shape this update supports.
  foreach (is_array($context) ? $context : [] as $source => $entry) {
    if (!in_array($source, $allowed_sources, TRUE)) {
      continue;
    }

    if (!is_array($entry)) {
      $entry = [];
    }

    $data = (string) ($entry['data'] ?? '');
    if (trim($data) === '') {
      $data = "{}\n";
    }

    $migrated[$source] = [
      'enabled' => (bool) ($entry['enabled'] ?? FALSE),
      'data' => $data,
    ];
  }

  ksort($migrated);
  $config->set('component_context', $migrated)->save(TRUE);
}

/**
 * Restore the uuid and _core hash stripped from the orchestrator by 0003.
 *
 * The 1.5.0/1.5.1 release of post_update 0003 replaced the whole record via
 * setData(), dropping the system-managed uuid and _core keys that the install
 * file omits. So regenerate both
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3591660
 */
function canvas_ai_post_update_0006_restore_orchestrator_agent_uuid(): void {
  $name = 'ai_agents.ai_agent.canvas_ai_orchestrator';
  $config = \Drupal::configFactory()->getEditable($name);
  if ($config->isNew()) {
    return;
  }

  $changed = FALSE;
  if (empty($config->get('uuid'))) {
    $config->set('uuid', \Drupal::service('uuid')->generate());
    $changed = TRUE;
  }
  if (empty($config->get('_core.default_config_hash'))) {
    // Recompute the hash exactly as core does when installing config
    // @see \Drupal\Core\Config\ConfigInstaller::createConfiguration()
    $module_path = \Drupal::service(ModuleExtensionList::class)->getPath('canvas_ai');
    $install = (new FileStorage($module_path . '/config/install'))->read($name);
    $config->set('_core.default_config_hash', Crypt::hashBase64(serialize($install)));
    $changed = TRUE;
  }
  if ($changed) {
    $config->save(TRUE);
  }
}

/**
 * Add block component props to saved component description settings.
 *
 * Block components previously stored only id/name/description. They now also
 * expose props, so rebuild the saved block data from the live system and merge
 * back any user-customized descriptions.
 *
 * @see \Drupal\canvas_ai\CanvasAiPageBuilderHelper::getEnabledBlockComponentsFromStorage()
 */
function canvas_ai_post_update_0007_add_block_props_to_component_description_settings(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.component_description.settings');
  if ($config->isNew()) {
    return;
  }

  $source = BlockComponent::SOURCE_PLUGIN_ID;
  $saved_data = (string) $config->get("component_context.$source.data");
  // Nothing to migrate when the site never saved any block data.
  if ($saved_data === '') {
    return;
  }

  $page_builder_helper = \Drupal::service('canvas_ai.page_builder_helper');
  assert($page_builder_helper instanceof CanvasAiPageBuilderHelper);
  $rebuilt_blocks = $page_builder_helper->getEnabledBlockComponentsFromStorage();
  // Without live block data there are no props to add.
  if ($rebuilt_blocks === []) {
    return;
  }

  // The rebuilt data already carries the new props and their default
  // descriptions. Layer each block's previously saved description back on top.
  $decoded = Yaml::decode($saved_data);
  $saved_blocks = is_array($decoded) ? $decoded : [];
  foreach ($saved_blocks as $block_id => $saved_block) {
    if (isset($rebuilt_blocks[$block_id], $saved_block['description'])) {
      $rebuilt_blocks[$block_id]['description'] = $saved_block['description'];
    }
  }

  // Replace only the block data; the enabled flag is left untouched.
  $config->set("component_context.$source.data", Yaml::encode($rebuilt_blocks))->save(TRUE);
}

/**
 * Reimport the component agent as its system prompt and tokens have changed.
 *
 * The conditional state instructions were moved out of the system prompt into
 * a dynamic section injected through the new component_agent_dynamic_state
 * token, so existing sites need the stored agent config refreshed.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3584136
 */
function canvas_ai_post_update_0008_reimport_component_agent(): void {
  $module_path = \Drupal::service(ModuleExtensionList::class)->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $data = $source->read('ai_agents.ai_agent.canvas_component_agent');
  $config = \Drupal::configFactory()->getEditable('ai_agents.ai_agent.canvas_component_agent');
  if ($data && !$config->isNew()) {
    // Only the system prompt and tool usage limits changed.
    $config
      ->set('system_prompt', $data['system_prompt'])
      ->set('tool_usage_limits', $data['tool_usage_limits'])
      ->save(TRUE);

    $message = 'The Canvas component agent system prompt has been updated. If you had customized it directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}

/**
 * Remove the obsolete theme-region-keyed AI descriptions.
 *
 * Page variants replaced theme regions, so the settings form now stores
 * page-variant descriptions under `variant_descriptions`. The old
 * `region_descriptions` key is no longer read or written; drop it so active
 * configuration matches the schema. The old region descriptions described theme
 * regions that no longer drive rendering, so they are discarded rather than
 * migrated.
 */
function canvas_ai_post_update_0009_remove_region_descriptions(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.theme_region.settings');
  if (!$config->isNew() && $config->get('region_descriptions') !== NULL) {
    $config->clear('region_descriptions')->save(TRUE);
  }
}

/**
 * Rename the AI page-variant settings object off its theme-region-era name.
 *
 * The settings stored under `canvas_ai.theme_region.settings` have described
 * page variants (not theme regions) since page variants replaced regions;
 * only the config name lagged behind. Move the object (and its translation
 * overrides in every language collection) to `canvas_ai.page_variant.settings`
 * so the name matches what it holds.
 */
function canvas_ai_post_update_0010_rename_page_variant_settings(): void {
  $storage = \Drupal::service(StorageCacheInterface::class);
  \assert($storage instanceof StorageInterface);
  foreach (['', ...$storage->getAllCollectionNames()] as $collection) {
    $collection_storage = $collection === '' ? $storage : $storage->createCollection($collection);
    $data = $collection_storage->read('canvas_ai.theme_region.settings');
    if (\is_array($data)) {
      $collection_storage->write('canvas_ai.page_variant.settings', $data);
      $collection_storage->delete('canvas_ai.theme_region.settings');
    }
  }
}

/**
 * Reimport default agents to pick up the latest ai_agents schema.
 *
 * A drupal/ai_agents upgrade added new per-tool settings
 * (restrict_multiple_calls, multiple_call_error_message) to every agent's
 * existing tools, a new guardrail_set key, and a simplified tool_usage_limits
 * shape. It also carries system prompt refinements for each default agent.
 * Update only these known keys, leaving the rest of each record (including
 * uuid and _core) untouched.
 */
function canvas_ai_post_update_0011_reimport_default_agents(): void {
  $module_path = \Drupal::service(ModuleExtensionList::class)->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $config_factory = \Drupal::configFactory();

  $agent_ids = [
    'canvas_ai_orchestrator',
    'canvas_metadata_generation_agent',
    'canvas_page_builder_agent',
    'canvas_template_builder_agent',
    'canvas_title_generation_agent',
    'canvas_component_agent',
  ];

  foreach ($agent_ids as $agent_id) {
    $name = "ai_agents.ai_agent.$agent_id";
    $data = $source->read($name);
    $config = $config_factory->getEditable($name);
    if (!$data || $config->isNew()) {
      continue;
    }

    $config->set('system_prompt', $data['system_prompt']);
    $config->set('tool_usage_limits', $data['tool_usage_limits']);
    $config->set('guardrail_set', $data['guardrail_set'] ?? '');

    foreach (array_keys($config->get('tools') ?? []) as $tool_id) {
      $config->set("tool_settings.$tool_id.restrict_multiple_calls", $data['tool_settings'][$tool_id]['restrict_multiple_calls'] ?? 0);
      $config->set("tool_settings.$tool_id.multiple_call_error_message", $data['tool_settings'][$tool_id]['multiple_call_error_message'] ?? '');
    }

    $config->save(TRUE);
  }

  $message = 'The Canvas AI default agents have been updated to match latest AI Agent schema updates. If you had customized them directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
  \Drupal::logger('canvas_ai')->warning($message);
}

/**
 * Reimport the page and template builder agents as their prompts changed.
 *
 * Both prompts now state that the content region is the only region where
 * components can be placed; the template builder adds header, navigation,
 * footer or sidebar sections only when the user explicitly asks for them,
 * still in the content region. The region-specific instructions and the
 * [canvas_ai:available_regions] token were removed from both system prompts,
 * and the template builder's description no longer mentions regions.
 *
 * Sites that update after this change already get the new prompts from 0011,
 * which re-imports every agent's system prompt but not the template builder's
 * description. Sites that ran 0011 before the prompts changed get both here.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3592030
 */
function canvas_ai_post_update_0012_reimport_region_free_builder_agents(): void {
  $module_path = \Drupal::service(ModuleExtensionList::class)->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $changed_keys = [
    'ai_agents.ai_agent.canvas_page_builder_agent' => ['system_prompt'],
    'ai_agents.ai_agent.canvas_template_builder_agent' => ['system_prompt', 'description'],
  ];
  $updated = FALSE;
  foreach ($changed_keys as $name => $keys) {
    $data = $source->read($name);
    $config = \Drupal::configFactory()->getEditable($name);
    if (!$data || $config->isNew()) {
      continue;
    }
    // Set only the changed keys so the per-site uuid, _core hash, and any
    // other fields stay intact.
    foreach ($keys as $key) {
      $config->set($key, $data[$key]);
    }
    $config->save(TRUE);
    $updated = TRUE;
  }
  if ($updated) {
    $message = 'The Canvas AI page builder and template builder agent system prompts have been updated. If you had customized them directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}

/**
 * Delete the unused AI page variant descriptions.
 *
 * No agent reads canvas_ai.page_variant.settings anymore: the descriptions
 * only fed the removed [canvas_ai:available_regions] token, and the settings
 * form that wrote them is gone. Drop the object (and its translation overrides
 * in every language collection) and rebuild the router, as the form's route
 * and local task were removed too.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3592030
 */
function canvas_ai_post_update_0013_delete_page_variant_settings(): void {
  $storage = \Drupal::service(StorageCacheInterface::class);
  \assert($storage instanceof StorageInterface);
  foreach (['', ...$storage->getAllCollectionNames()] as $collection) {
    $collection_storage = $collection === '' ? $storage : $storage->createCollection($collection);
    if ($collection_storage->exists('canvas_ai.page_variant.settings')) {
      $collection_storage->delete('canvas_ai.page_variant.settings');
    }
  }
  \Drupal::configFactory()->reset('canvas_ai.page_variant.settings');
  \Drupal::service(RouteBuilderInterface::class)->rebuild();
}
