<?php

// phpcs:ignoreFile
// GENERATED by scripts/generate-date-fallback-patterns.php. Do not edit.

declare(strict_types=1);

namespace Drupal\canvas\Utility;

/**
 * Short date/time patterns for when the intl PHP extension is unavailable.
 *
 * Generated from ICU data by scripts/generate-date-fallback-patterns.php. Each
 * row holds PHP date() patterns whose output is identical to
 * \IntlDateFormatter's SHORT output for that langcode. Langcodes whose ICU
 * output date() cannot reproduce (native digits, localized AM/PM text) are
 * not listed.
 *
 * @internal
 */
final class DateFallbackPatterns {

  /**
   * The ICU version the patterns were generated from.
   */
  public const string ICU_VERSION = '77.1';

  /**
   * Patterns keyed by lowercase Drupal langcode.
   *
   * @var array<string, array{date: string, date_time: string, time: string}>
   */
  public const array PATTERNS = [
    'af' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'ast' => ['date' => 'j/n/y', 'date_time' => 'j/n/y H:i', 'time' => 'H:i'],
    'az' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'be' => ['date' => 'j.m.y', 'date_time' => 'j.m.y, H:i', 'time' => 'H:i'],
    'bg' => ['date' => 'j.m.y г.', 'date_time' => 'j.m.y г., G:i', 'time' => 'G:i'],
    'bo' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'br' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y H:i', 'time' => 'H:i'],
    'bs' => ['date' => 'j. n. Y.', 'date_time' => 'j. n. Y. \\u H:i', 'time' => 'H:i'],
    'ca' => ['date' => 'j/n/y', 'date_time' => 'j/n/y G:i', 'time' => 'G:i'],
    'cs' => ['date' => 'd.m.y', 'date_time' => 'd.m.y G:i', 'time' => 'G:i'],
    'cy' => ['date' => 'd/m/y', 'date_time' => 'd/m/y, H:i', 'time' => 'H:i'],
    'da' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y, H.i', 'time' => 'H.i'],
    'de' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'en' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, g:i A', 'time' => 'g:i A'],
    'en-gb' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'en-x-simple' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, g:i A', 'time' => 'g:i A'],
    'eo' => ['date' => 'y-m-d', 'date_time' => 'y-m-d H:i', 'time' => 'H:i'],
    'es' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, G:i', 'time' => 'G:i'],
    'et' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'eu' => ['date' => 'y/n/j', 'date_time' => 'y/n/j (H:i)', 'time' => 'H:i'],
    'fi' => ['date' => 'j.n.Y', 'date_time' => 'j.n.Y \\k\\l\\o G.i', 'time' => 'G.i'],
    'fil' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, g:i A', 'time' => 'g:i A'],
    'fo' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'fr' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y H:i', 'time' => 'H:i'],
    'fy' => ['date' => 'd-m-y', 'date_time' => 'd-m-y H:i', 'time' => 'H:i'],
    'ga' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'gd' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'gl' => ['date' => 'd/m/y', 'date_time' => 'd/m/y, H:i', 'time' => 'H:i'],
    'gsw-berne' => ['date' => 'd.m.y', 'date_time' => 'd.m.y H:i', 'time' => 'H:i'],
    'gu' => ['date' => 'j/n/y', 'date_time' => 'j/n/y h:i A', 'time' => 'h:i A'],
    'he' => ['date' => 'j.n.Y', 'date_time' => 'j.n.Y, G:i', 'time' => 'G:i'],
    'hi' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, g:i a', 'time' => 'g:i a'],
    'hr' => ['date' => 'd. m. Y.', 'date_time' => 'd. m. Y. H:i', 'time' => 'H:i'],
    'ht' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y H:i', 'time' => 'H:i'],
    'hu' => ['date' => 'Y. m. d.', 'date_time' => 'Y. m. d. G:i', 'time' => 'G:i'],
    'hy' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'id' => ['date' => 'd/m/y', 'date_time' => 'd/m/y, H.i', 'time' => 'H.i'],
    'is' => ['date' => 'j.n.Y', 'date_time' => 'j.n.Y, H:i', 'time' => 'H:i'],
    'it' => ['date' => 'd/m/y', 'date_time' => 'd/m/y, H:i', 'time' => 'H:i'],
    'ja' => ['date' => 'Y/m/d', 'date_time' => 'Y/m/d G:i', 'time' => 'G:i'],
    'jv' => ['date' => 'd-m-Y', 'date_time' => 'd-m-Y, H:i', 'time' => 'H:i'],
    'ka' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'kk' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'km' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, g:i A', 'time' => 'g:i A'],
    'kn' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, h:i A', 'time' => 'h:i A'],
    'ku' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y H:i', 'time' => 'H:i'],
    'ky' => ['date' => 'j/n/y', 'date_time' => 'j/n/y H:i', 'time' => 'H:i'],
    'lo' => ['date' => 'j/n/Y', 'date_time' => 'j/n/Y, G:i', 'time' => 'G:i'],
    'lt' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'lv' => ['date' => 'd.m.y', 'date_time' => 'd.m.y H:i', 'time' => 'H:i'],
    'mg' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'mk' => ['date' => 'j.n.y', 'date_time' => 'j.n.y, во H:i', 'time' => 'H:i'],
    'ml' => ['date' => 'j/n/y', 'date_time' => 'j/n/y g:i A', 'time' => 'g:i A'],
    'mn' => ['date' => 'Y.m.d', 'date_time' => 'Y.m.d H:i', 'time' => 'H:i'],
    'mt' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y H:i', 'time' => 'H:i'],
    'nb' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y, H:i', 'time' => 'H:i'],
    'nl' => ['date' => 'd-m-Y', 'date_time' => 'd-m-Y, H:i', 'time' => 'H:i'],
    'nn' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y, H:i', 'time' => 'H:i'],
    'oc' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'or' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, g:i A', 'time' => 'g:i A'],
    'os' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'pl' => ['date' => 'j.m.Y', 'date_time' => 'j.m.Y, H:i', 'time' => 'H:i'],
    'pt' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'pt-br' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'pt-pt' => ['date' => 'd/m/y', 'date_time' => 'd/m/y, H:i', 'time' => 'H:i'],
    'rm-rumgr' => ['date' => 'd-m-y', 'date_time' => 'd-m-y H:i', 'time' => 'H:i'],
    'ro' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y, H:i', 'time' => 'H:i'],
    'ru' => ['date' => 'd.m.Y', 'date_time' => 'd.m.Y, H:i', 'time' => 'H:i'],
    'rw' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'sco' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, H:i', 'time' => 'H:i'],
    'se' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'si' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d, H.i', 'time' => 'H.i'],
    'sk' => ['date' => 'j. n. Y', 'date_time' => 'j. n. Y G:i', 'time' => 'G:i'],
    'sl' => ['date' => 'j. n. y', 'date_time' => 'j. n. y, H:i', 'time' => 'H:i'],
    'sr' => ['date' => 'j. n. Y.', 'date_time' => 'j. n. Y. H:i', 'time' => 'H:i'],
    'sv' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d H:i', 'time' => 'H:i'],
    'sw' => ['date' => 'd/m/Y', 'date_time' => 'd/m/Y, H:i', 'time' => 'H:i'],
    'ta' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, g:i A', 'time' => 'g:i A'],
    'ta-lk' => ['date' => 'j/n/y', 'date_time' => 'j/n/y, H:i', 'time' => 'H:i'],
    'te' => ['date' => 'd-m-y', 'date_time' => 'd-m-y g:i A', 'time' => 'g:i A'],
    'th' => ['date' => 'j/n/y', 'date_time' => 'j/n/y H:i', 'time' => 'H:i'],
    'tr' => ['date' => 'j.m.Y', 'date_time' => 'j.m.Y H:i', 'time' => 'H:i'],
    'tyv' => ['date' => 'n/j/y', 'date_time' => 'n/j/y, H:i', 'time' => 'H:i'],
    'ug' => ['date' => 'Y-m-d', 'date_time' => 'Y-m-d، H:i', 'time' => 'H:i'],
    'uk' => ['date' => 'd.m.y', 'date_time' => 'd.m.y, H:i', 'time' => 'H:i'],
    'ur' => ['date' => 'j/n/y', 'date_time' => 'j/n/y، g:i A', 'time' => 'g:i A'],
    'vi' => ['date' => 'j/n/y', 'date_time' => 'H:i j/n/y', 'time' => 'H:i'],
    'zh-hans' => ['date' => 'Y/n/j', 'date_time' => 'Y/n/j H:i', 'time' => 'H:i'],
  ];

}
