#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { existsSync, realpathSync, watch } from 'node:fs';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildComponentRegistryModule,
  resolveComponentRegistrySourcePaths,
} from '@drupal-canvas/headless/component-registry';
import { buildComponentMetadataPayload } from '@drupal-canvas/headless/components-endpoint';

export async function generateCanvasSources(projectRoot = process.cwd()) {
  const modulePath = path.join(
    projectRoot,
    'src/canvas-components.generated.ts',
  );
  const [source, manifest] = await Promise.all([
    buildComponentRegistryModule({ projectRoot, modulePath }),
    buildComponentMetadataPayload({ projectRoot }),
  ]);
  await updateFile(
    modulePath,
    source.replace(/(from "[^"\n]+)\.ts";/g, '$1";'),
  );
  // A real server-only import embeds metadata in the deployment bundle; neither
  // discovery nor source paths enter its runtime graph. Do not import in main.ts.
  await updateFile(
    path.join(projectRoot, 'src/canvas-manifest.generated.ts'),
    `/** Generated by Canvas. Import only from server.ts. */\nimport type { ComponentMetadataPayload } from '@drupal-canvas/headless/components-endpoint/handler';\nconst manifest: ComponentMetadataPayload = ${JSON.stringify(manifest, null, 2)};\nexport default manifest;\n`,
  );
}
async function updateFile(file, content) {
  if ((await readFile(file, 'utf8').catch(() => null)) === content) return;
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file + '.tmp', content);
  await rename(file + '.tmp', file);
}

/** Watch only configured component sources and config, not node_modules/output. */
export async function watchCanvasSources(
  projectRoot = process.cwd(),
  onError = console.error,
) {
  let closed = false;
  let timer;
  let active = Promise.resolve();
  let sources;
  const schedule = () => {
    if (closed) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      active = active
        .then(async () => {
          if (closed) return;
          // Subscribe to the configured location even when its metadata is
          // invalid. Fixing a file there must recover without editing config again.
          subscribe();
          await generateCanvasSources(projectRoot);
        })
        .catch(onError);
    }, 75);
  };
  const subscribe = () => {
    sources?.close();
    const { componentRoot } = resolveComponentRegistrySourcePaths({
      projectRoot,
    });
    let root = componentRoot;
    while (!existsSync(root)) root = path.dirname(root);
    sources = watch(root, { recursive: root === componentRoot }, schedule);
    sources.on('error', onError);
  };
  const config = watch(projectRoot, (_event, filename) => {
    if (filename?.toString() === 'canvas.config.json') schedule();
  });
  config.on('error', onError);
  try {
    subscribe();
    await generateCanvasSources(projectRoot);
  } catch (error) {
    config.close();
    sources?.close();
    throw error;
  }
  return async () => {
    closed = true;
    clearTimeout(timer);
    config.close();
    sources?.close();
    await active;
  };
}

// npm invokes bins through node_modules/.bin symlinks. Node resolves the module
// URL, but argv[1] can retain the symlink; normalize both before comparing.
function isEntrypoint() {
  if (!process.argv[1]) return false;
  try {
    return (
      realpathSync(process.argv[1]) ===
      realpathSync(fileURLToPath(import.meta.url))
    );
  } catch {
    return false;
  }
}

if (isEntrypoint()) {
  const args = process.argv.slice(2);
  const separator = args.indexOf('--');
  const command = separator < 0 ? [] : args.slice(separator + 1);
  const stop = args.includes('--watch')
    ? await watchCanvasSources()
    : (await generateCanvasSources(), async () => {});
  if (command.length) {
    const child = spawn(command[0], command.slice(1), { stdio: 'inherit' });
    for (const signal of ['SIGINT', 'SIGTERM'])
      process.once(signal, () => {
        child.kill(signal);
        void stop();
      });
    child.once('error', async (error) => {
      console.error(error);
      await stop();
      process.exitCode = 1;
    });
    child.once('exit', async (code) => {
      await stop();
      process.exitCode = code ?? 1;
    });
  } else if (args.includes('--watch')) {
    for (const signal of ['SIGINT', 'SIGTERM'])
      process.once(signal, () => {
        void stop();
      });
  }
}
